version: '3.8'

services:
  db:
    image: postgres:15
    container_name: safety_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: safety_analysis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Veritabanını tarayıcıdan yönetmek için arayüz (Opsiyonel ama önerilir)
  pgadmin:
    image: dpage/pgadmin4
    container_name: safety_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: